export default {
  login: 'snitin315',
  id: 6599979,
  node_id: 'MDQ6VXNlcjY1OTk5Nzk=',
  avatar_url: 'https://avatars2.githubusercontent.com/u/6599979?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/snitin315',
  html_url: 'https://github.com/snitin315',
  followers_url: 'https://api.github.com/users/snitin315/followers',
  following_url: 'https://api.github.com/users/snitin315/following{/other_user}',
  gists_url: 'https://api.github.com/users/snitin315/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/snitin315/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/snitin315/subscriptions',
  organizations_url: 'https://api.github.com/users/snitin315/orgs',
  repos_url: 'https://api.github.com/users/snitin315/repos',
  events_url: 'https://api.github.com/users/snitin315/events{/privacy}',
  received_events_url: 'https://api.github.com/users/snitin315/received_events',
  type: 'User',
  site_admin: false,
  name: 'Nitin Kumar',
  company: '@Upstatement ',
  blog: 'https://snitin315.now.sh',
  location: 'New Delhi, India',
  email: null,
  hireable: true,
  bio: null,
  public_repos: 70,
  public_gists: 4,
  followers: 11,
  following: 9,
};
