export default [
  {
    id: 168088328,
    node_id: 'MDEwOlJlcG9zaXRvcnkxNjgwODgzMjg=',
    name: 'universal-inovators',
    full_name: 'snitin315/universal-inovators',
    private: false,
    owner: {
      login: 'snitin315',
      id: 6599979,
      node_id: 'MDQ6VXNlcjY1OTk5Nzk=',
      avatar_url: 'https://avatars2.githubusercontent.com/u/6599979?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/snitin315',
      html_url: 'https://github.com/snitin315',
      followers_url: 'https://api.github.com/users/snitin315/followers',
      following_url: 'https://api.github.com/users/snitin315/following{/other_user}',
      gists_url: 'https://api.github.com/users/snitin315/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/snitin315/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/snitin315/subscriptions',
      organizations_url: 'https://api.github.com/users/snitin315/orgs',
      repos_url: 'https://api.github.com/users/snitin315/repos',
      events_url: 'https://api.github.com/users/snitin315/events{/privacy}',
      received_events_url: 'https://api.github.com/users/snitin315/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/snitin315/universal-inovators',
    description: 'Starter Files and Solutions for Full Stack Advanced React and GraphQL ',
    fork: true,
    url: 'https://api.github.com/repos/snitin315/universal-inovators',
    forks_url: 'https://api.github.com/repos/snitin315/universal-inovators/forks',
    keys_url: 'https://api.github.com/repos/snitin315/universal-inovators/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/snitin315/universal-inovators/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/snitin315/universal-inovators/teams',
    hooks_url: 'https://api.github.com/repos/snitin315/universal-inovators/hooks',
    issue_events_url:
      'https://api.github.com/repos/snitin315/universal-inovators/issues/events{/number}',
    events_url: 'https://api.github.com/repos/snitin315/universal-inovators/events',
    assignees_url: 'https://api.github.com/repos/snitin315/universal-inovators/assignees{/user}',
    branches_url: 'https://api.github.com/repos/snitin315/universal-inovators/branches{/branch}',
    tags_url: 'https://api.github.com/repos/snitin315/universal-inovators/tags',
    blobs_url: 'https://api.github.com/repos/snitin315/universal-inovators/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/snitin315/universal-inovators/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/snitin315/universal-inovators/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/snitin315/universal-inovators/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/snitin315/universal-inovators/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/snitin315/universal-inovators/languages',
    stargazers_url: 'https://api.github.com/repos/snitin315/universal-inovators/stargazers',
    contributors_url: 'https://api.github.com/repos/snitin315/universal-inovators/contributors',
    subscribers_url: 'https://api.github.com/repos/snitin315/universal-inovators/subscribers',
    subscription_url: 'https://api.github.com/repos/snitin315/universal-inovators/subscription',
    commits_url: 'https://api.github.com/repos/snitin315/universal-inovators/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/snitin315/universal-inovators/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/snitin315/universal-inovators/comments{/number}',
    issue_comment_url:
      'https://api.github.com/repos/snitin315/universal-inovators/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/snitin315/universal-inovators/contents/{+path}',
    compare_url:
      'https://api.github.com/repos/snitin315/universal-inovators/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/snitin315/universal-inovators/merges',
    archive_url:
      'https://api.github.com/repos/snitin315/universal-inovators/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/snitin315/universal-inovators/downloads',
    issues_url: 'https://api.github.com/repos/snitin315/universal-inovators/issues{/number}',
    pulls_url: 'https://api.github.com/repos/snitin315/universal-inovators/pulls{/number}',
    milestones_url:
      'https://api.github.com/repos/snitin315/universal-inovators/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/snitin315/universal-inovators/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/snitin315/universal-inovators/labels{/name}',
    releases_url: 'https://api.github.com/repos/snitin315/universal-inovators/releases{/id}',
    deployments_url: 'https://api.github.com/repos/snitin315/universal-inovators/deployments',
    created_at: '2019-01-29T04:21:52Z',
    updated_at: '2019-04-09T03:36:55Z',
    pushed_at: '2019-04-09T03:36:52Z',
    git_url: 'git://github.com/snitin315/universal-inovators.git',
    ssh_url: 'git@github.com:snitin315/universal-inovators.git',
    clone_url: 'https://github.com/snitin315/universal-inovators.git',
    svn_url: 'https://github.com/snitin315/universal-inovators',
    homepage: 'https://AdvancedReact.com',
    size: 5132,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
];
